import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm
from matplotlib.patches import Patch


def plot_residue_score_map_with_strips(
    csv_file,
    protein_name,
    save_path=None,
    threshold=0.5,
    high_conf=0.7,
    smooth_window=None,
    show=False
):
    """
    Plot residue-level binding score map with true-label strip
    and TP/TN/FP/FN classification strip.

    Parameters
    ----------
    csv_file : str
        CSV file generated by test_case_study().
    protein_name : str
        Protein name to visualize.
    save_path : str or None
        Path to save figure.
    threshold : float
        Decision threshold.
    high_conf : float
        High-confidence region threshold.
    smooth_window : int or None
        If not None, add a moving-average curve.
    show : bool
        Whether to display the figure. For batch plotting, use show=False.
    """

    # ----------------------------
    # Color palette
    # ----------------------------
    COLORS = {
        'score': '#2F4B7C',        # deep blue
        'binding': '#D62728',      # red
        'threshold': '#4D4D4D',    # dark gray
        'high_conf': '#F2C94C',    # light yellow

        'true_bg': '#F2F2F2',      # light gray
        'true_pos': '#D62728',     # red

        'TN': '#D9D9D9',           # gray
        'TP': '#009E73',           # green
        'FP': '#E69F00',           # orange
        'FN': '#CC79A7'            # purple-red
    }

    df = pd.read_csv(csv_file)
    sub = df[df['protein'] == protein_name].copy()

    if sub.empty:
        raise ValueError(f'Protein "{protein_name}" not found in {csv_file}.')

    sub = sub.sort_values('residue_index')

    x = sub['residue_index'].values
    prob = sub['pred_prob'].values
    true_label = sub['true_label'].values.astype(int)
    pred_label = sub['pred_label'].values.astype(int)

    # 如果 CSV 中没有 category，则自动计算
    if 'category' not in sub.columns:
        categories = []
        for y_true, y_pred in zip(true_label, pred_label):
            if y_true == 1 and y_pred == 1:
                categories.append('TP')
            elif y_true == 0 and y_pred == 0:
                categories.append('TN')
            elif y_true == 0 and y_pred == 1:
                categories.append('FP')
            else:
                categories.append('FN')
        sub['category'] = categories

    category = sub['category'].values

    cat_to_code = {
        'TN': 0,
        'TP': 1,
        'FP': 2,
        'FN': 3
    }

    cat_code = np.array([cat_to_code[c] for c in category]).reshape(1, -1)
    true_arr = true_label.reshape(1, -1)

    # ----------------------------
    # Figure layout
    # ----------------------------
    fig = plt.figure(figsize=(11, 4.4))
    gs = fig.add_gridspec(
        nrows=3,
        ncols=1,
        height_ratios=[4.0, 0.35, 0.35],
        hspace=0.10
    )

    ax1 = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1], sharex=ax1)
    ax3 = fig.add_subplot(gs[2], sharex=ax1)

    # ----------------------------
    # 上方：predicted binding score
    # ----------------------------
    ax1.plot(
        x,
        prob,
        linewidth=1.8,
        color=COLORS['score'],
        label='Binding score'
    )

    # 真实结合残基点
    ax1.scatter(
        x[true_label == 1],
        prob[true_label == 1],
        s=32,
        marker='o',
        color=COLORS['binding'],
        edgecolors='black',
        linewidths=0.35,
        zorder=4,
        label='True binding residues'
    )

    # 阈值线
    ax1.axhline(
        threshold,
        linestyle='--',
        linewidth=1.1,
        color=COLORS['threshold'],
        alpha=0.85,
        label=f'Threshold = {threshold}'
    )

    # 高置信区域
    ax1.axhspan(
        high_conf,
        1.0,
        color=COLORS['high_conf'],
        alpha=0.13,
        label=f'High-confidence region ($p \\geq {high_conf}$)'
    )

    # 可选平滑曲线
    if smooth_window is not None and smooth_window > 1:
        smooth_prob = (
            pd.Series(prob)
            .rolling(window=smooth_window, center=True, min_periods=1)
            .mean()
            .values
        )

        ax1.plot(
            x,
            smooth_prob,
            linewidth=1.2,
            linestyle=':',
            color='#000000',
            alpha=0.85,
            label=f'Moving average (window={smooth_window})'
        )

    ax1.set_ylabel('Binding score', fontsize=10)
    ax1.set_ylim(-0.03, 1.05)
    ax1.set_xlim(x.min(), x.max())
    ax1.set_title(protein_name, fontsize=11, fontweight='bold')

    # 淡网格
    ax1.grid(axis='y', linestyle='--', linewidth=0.5, alpha=0.25)

    # 去掉上右边框
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)

    ax1.legend(
        frameon=False,
        fontsize=8,
        ncol=2,
        loc='upper right'
    )

    # ----------------------------
    # 中间：true label strip
    # ----------------------------
    true_cmap = ListedColormap([
        COLORS['true_bg'],
        COLORS['true_pos']
    ])
    true_norm = BoundaryNorm([-0.5, 0.5, 1.5], true_cmap.N)

    ax2.imshow(
        true_arr,
        aspect='auto',
        cmap=true_cmap,
        norm=true_norm,
        extent=[x.min() - 0.5, x.max() + 0.5, 0, 1]
    )

    ax2.set_yticks([])
    ax2.set_ylabel('True', rotation=0, labelpad=28, va='center', fontsize=9)
    ax2.tick_params(axis='x', which='both', bottom=False, labelbottom=False)

    for spine in ax2.spines.values():
        spine.set_visible(False)

    # ----------------------------
    # 下方：TP/TN/FP/FN strip
    # ----------------------------
    cat_cmap = ListedColormap([
        COLORS['TN'],
        COLORS['TP'],
        COLORS['FP'],
        COLORS['FN']
    ])
    cat_norm = BoundaryNorm([-0.5, 0.5, 1.5, 2.5, 3.5], cat_cmap.N)

    ax3.imshow(
        cat_code,
        aspect='auto',
        cmap=cat_cmap,
        norm=cat_norm,
        extent=[x.min() - 0.5, x.max() + 0.5, 0, 1]
    )

    ax3.set_yticks([])
    ax3.set_ylabel('Class', rotation=0, labelpad=28, va='center', fontsize=9)
    ax3.set_xlabel('Residue index', fontsize=10)

    for spine in ax3.spines.values():
        spine.set_visible(False)

    legend_elements = [
        Patch(facecolor=COLORS['TN'], label='TN'),
        Patch(facecolor=COLORS['TP'], label='TP'),
        Patch(facecolor=COLORS['FP'], label='FP'),
        Patch(facecolor=COLORS['FN'], label='FN')
    ]

    ax3.legend(
        handles=legend_elements,
        frameon=False,
        fontsize=8,
        ncol=4,
        loc='upper right',
        bbox_to_anchor=(1.0, -0.55)
    )

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=600, bbox_inches='tight')

        # 同时保存 pdf，方便论文排版
        if save_path.lower().endswith('.png'):
            pdf_path = save_path[:-4] + '.pdf'
            plt.savefig(pdf_path, bbox_inches='tight')

    if show:
        plt.show()

    plt.close(fig)

# 完整的蛋白质列表
# protein_list = [
#     '3J8Y_K', '3J94_A', '4D79_C', '4RQV_A', '4RV7_C', '4RX6_B',
#     '4S1K_A', '4WVY_A', '4WZY_A', '4X2D_A', '4XBR_A', '4XHO_A',
#     '4XJX_B', '4XRU_A', '4XRU_B', '4XVU_H', '4YB7_A', '4YDS_A',
#     '4ZGN_A', '4ZS4_B', '5A98_A', '5A99_A', '5APB_A', '5BSM_A',
#     '5BUR_A', '5COU_A', '5CYR_B', '5D15_B', '5D1O_A', '5D6J_A',
#     '5D9H_B', '5DB4_A', '5DN3_A', '5DN6_A', '5E3I_B', '5E84_F',
#     '5ECK_A', '5EOU_B', '5ETL_D', '5EWG_A', '5F1C_B'
# ]

# 完整的蛋白质列表
protein_list = [
    '1ak4__D', '1b6c__A', '1f60__B', '1jtd__B', '1k5d_A_B', '1ktz__A', '1mah__F', '1ml0__D', '1nrj__A', '1nrj__B',
    '1pxv__A', '1qa9__A', '1svd__M', '1u0s__A', '1z0j__B', '1zbd__B', '2a9k__A', '2b42__A', '2d5r__A', '2doh__X',
    '2f91__A', '2fp4__A', '2g2u__B', '2h0d__B', '2p7v__A', '2v4z__B', '2v8s__V', '2v9t__A', '3ANW__B', '3AYH__B',
    '3B08__B', '3MDB__C', '3MMY__A', '3OUR__B', '3PH0__A', '3PV6__A', '3SHG__A', '3UVJ__A', '3VDO__B', '3VU9__A',
    '3VZ9__D', '3W2W__B', '3ZEU__D', '3ZKQ__A', '3beg__B', '3c5t__A', '3cf4__G', '3cx8__B', '3czu__B', '3d7v__A',
    '3dlq__I', '3e1z__B', '3e5a__A', '3gni__A', '4APX__A', '4AWX__B', '4BH6__D', '4BH6__L', '4BI8__A', '4BI8__B',
    '4BJJ__B', '4DFC__B', '4FQ0__B', '4H3K__A', '4H3K__B', '4IU2__A', '4JE3__B', '4KT3__B', '4KT6__B', '4apx__A',  # 注意 4APX__A 已存在，此处为原列表中的小写 a，按原样保留
    '4awx__B', '4bh6__D', '4bh6__L', '4bi8__A', '4bi8__B', '4bjj__B', '4dfc__B', '4fq0__B', '4h3k__A', '4h3k__B',
    '4iu2__A', '4je3__B', '4kt3__B', '4kt6__B', '7cei__A'
]

# CSV 文件路径（您的原始文件）
# csv_file = 'case_study_PPI_3_2026-06-13 17_47_26.048495(test).csv'
# csv_file = 'case_study1_PPI_1_2026-06-13 18_04_54.490447(test).csv'
csv_file = 'case_study_PPI_0_2026-06-16 15_52_21.349233.csv'

# 批量绘制并保存
for protein_name in protein_list:
    save_path = f'case_PPI_score_map_{protein_name}.png'
    print(f"正在绘制: {protein_name}")
    try:
        plot_residue_score_map_with_strips(
            csv_file=csv_file,
            protein_name=protein_name,
            save_path=save_path
        )
        print(f"已保存: {save_path}")
    except Exception as e:
        print(f"绘制 {protein_name} 时出错: {e}")